In [1]:
import pandas as pd
from google.colab import drive
import random
import numpy as np
import torch

drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
user_df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Khuad_최종플젝/silver_gold_half_with_tag.csv')

In [3]:
user_df

,Unnamed: 0,id_to_index,handle,solvedCount,voteCount,class,rivalCount,reverseRivalCount,tier,rating,...,coins,stardusts,joinedAt,bannedUntil,proUntil,rank,isRival,isReverseRival,target,tag
0,0,1,cheon4050,240.0,0.0,5.0,0.0,0.0,15.0,1599.0,...,0.0,10155.0,2021-06-19T00:00:00.000Z,1970-01-01T00:00:00.000Z,1970-01-01T00:00:00.000Z,5997.0,0.0,0.0,0,"[['implementation', 'arithmetic', 'math']]"
1,1,1,cheon4050,240.0,0.0,5.0,0.0,0.0,15.0,1599.0,...,0.0,10155.0,2021-06-19T00:00:00.000Z,1970-01-01T00:00:00.000Z,1970-01-01T00:00:00.000Z,5997.0,0.0,0.0,3,[['dp']]
2,2,1,cheon4050,240.0,0.0,5.0,0.0,0.0,15.0,1599.0,...,0.0,10155.0,2021-06-19T00:00:00.000Z,1970-01-01T00:00:00.000Z,1970-01-01T00:00:00.000Z,5997.0,0.0,0.0,5,"[['dp', 'graphs', 'topological_sorting']]"
3,3,1,cheon4050,240.0,0.0,5.0,0.0,0.0,15.0,1599.0,...,0.0,10155.0,2021-06-19T00:00:00.000Z,1970-01-01T00:00:00.000Z,1970-01-01T00:00:00.000Z,5997.0,0.0,0.0,7,"[['bruteforcing', 'math']]"
4,4,1,cheon4050,240.0,0.0,5.0,0.0,0.0,15.0,1599.0,...,0.0,10155.0,2021-06-19T00:00:00.000Z,1970-01-01T00:00:00.000Z,1970-01-01T00:00:00.000Z,5997.0,0.0,0.0,8,"[['implementation', 'arithmetic', 'math']]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2707128,2707128,67299,yuiop7037,63.0,0.0,1.0,0.0,0.0,6.0,200.0,...,0.0,2130.0,2023-06-07T01:13:41.576Z,1970-01-01T00:00:00.000Z,1970-01-01T00:00:00.000Z,73263.0,0.0,0.0,0,"[['implementation', 'arithmetic', 'math']]"
2707129,2707129,67299,yuiop7037,63.0,0.0,1.0,0.0,0.0,6.0,200.0,...,0.0,2130.0,2023-06-07T01:13:41.576Z,1970-01-01T00:00:00.000Z,1970-01-01T00:00:00.000Z,73263.0,0.0,0.0,1,"[['implementation', 'arithmetic', 'math']]"
2707130,2707130,67299,yuiop7037,63.0,0.0,1.0,0.0,0.0,6.0,200.0,...,0.0,2130.0,2023-06-07T01:13:41.576Z,1970-01-01T00:00:00.000Z,1970-01-01T00:00:00.000Z,73263.0,0.0,0.0,8,"[['implementation', 'arithmetic', 'math']]"
2707131,2707131,67299,yuiop7037,63.0,0.0,1.0,0.0,0.0,6.0,200.0,...,0.0,2130.0,2023-06-07T01:13:41.576Z,1970-01-01T00:00:00.000Z,1970-01-01T00:00:00.000Z,73263.0,0.0,0.0,1487,[['implementation']]
2707132,2707132,67299,yuiop7037,63.0,0.0,1.0,0.0,0.0,6.0,200.0,...,0.0,2130.0,2023-06-07T01:13:41.576Z,1970-01-01T00:00:00.000Z,1970-01-01T00:00:00.000Z,73263.0,0.0,0.0,3633,"[['implementation', 'sorting']]"

## 문제 데이터 전처리

#### 문제 200개 이상 문제에 포함된 Tag 추출

In [4]:
problem_df = user_df[['target','tag']]

In [5]:
problem_df = problem_df.drop_duplicates()

In [6]:
problem_df = problem_df.sort_values(by='target').reset_index(drop = True)

In [7]:
problem_df

      target                                         tag
0          0  [['implementation', 'arithmetic', 'math']]
1          1  [['implementation', 'arithmetic', 'math']]
2          2         [['case_work', 'geometry', 'math']]
3          3                                    [['dp']]
4          4                      [['geometry', 'math']]
...      ...                                         ...
5534    7621                                        None
5535    7622                                        None
5536    7625                                        None
5537    7626                                        None
5538    7627                                        None

[5539 rows x 2 columns]

In [8]:
tag_list = []
for i in problem_df['tag']:
  i = i.replace("[[", "").replace("'","")
  i = i.replace("]]", "")
  tag_list.append(i)

In [10]:
problem_df['tag'] = tag_list

In [11]:
problem_df

      target                               tag
0          0  implementation, arithmetic, math
1          1  implementation, arithmetic, math
2          2         case_work, geometry, math
3          3                                dp
4          4                    geometry, math
...      ...                               ...
5534    7621                              None
5535    7622                              None
5536    7625                              None
5537    7626                              None
5538    7627                              None

[5539 rows x 2 columns]

In [12]:
tag_problem_df = problem_df['tag'].str.split(",",expand=True) #split에서 expand=True를 넣어서 split한 후에 값들을 모아둠

In [13]:
tag_problem_df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,implementation,arithmetic,math,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
1,implementation,arithmetic,math,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
2,case_work,geometry,math,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
3,dp,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
4,geometry,math,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5534,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
5535,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
5536,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
5537,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None
5538,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None

In [14]:
df_result = tag_problem_df[0].value_counts()

for column_name in tag_problem_df.columns[1:]:
  df_result = pd.concat([df_result, tag_problem_df[column_name].value_counts()],axis=1)

In [15]:
df_result.fillna(0)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
implementation,620.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
dp,610.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
data_structures,563.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
None,397.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
bruteforcing,339.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
suffix_tree,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
utf8,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
offline_dynamic_connectivity,0.0,0.0,0.0,0.0,3.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
tree_compression,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
general_matching,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [16]:
df_result['합'] = df_result[tag_problem_df.columns].sum(axis=1)

In [17]:
df_result = df_result.drop(index='None')

In [18]:
df_result = df_result.sort_values(by='합', ascending=False)

In [19]:
df_result

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,합
math,NaN,587.0,430.0,107.0,26.0,13.0,1.0,1.0,1.0,NaN,...,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1169.0
graphs,NaN,365.0,220.0,109.0,32.0,11.0,1.0,3.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,743.0
implementation,620.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,620.0
dp,610.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,610.0
data_structures,563.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,563.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
chordal_graph,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
permutation_cycle_decomposition,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
general_matching,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
dominator_tree,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0
general_matching,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0

In [20]:
tag_df = df_result[df_result["합"] >= 200]

In [21]:
#tag_idx : tag가 포함된 문제가 200 문제 이상인 Tag들의 모음
tag_idx = tag_df.index.to_list()
print(tag_idx)

[' math', ' graphs', 'implementation', 'dp', 'data_structures', ' implementation', ' graph_traversal', ' string', ' dp', ' sorting', 'bruteforcing', ' number_theory', ' trees', ' segtree', ' greedy', 'bfs', 'greedy', ' data_structures', 'math', 'binary_search', ' simulation']

In [22]:
print(len(tag_idx))

21

#### Tag-Problem Matrix 구성

In [23]:
df_tags = problem_df
df_tags['tag'] = df_tags['tag'].str.split(',')

In [24]:
df_tags = df_tags.explode('tag').dropna().reset_index(drop=True)
df_tags

       target             tag
0           0  implementation
1           0      arithmetic
2           0            math
3           1  implementation
4           1      arithmetic
...       ...             ...
14699    7621            None
14700    7622            None
14701    7625            None
14702    7626            None
14703    7627            None

[14704 rows x 2 columns]

In [25]:
df_tag = df_tags[df_tags['tag'].isin(tag_idx)].reset_index(drop=True)
df_tags.rename(columns={"Unnamed: 0":"Id_idx"},inplace = True)

In [26]:
df_tags

       target             tag
0           0  implementation
1           0      arithmetic
2           0            math
3           1  implementation
4           1      arithmetic
...       ...             ...
14699    7621            None
14700    7622            None
14701    7625            None
14702    7626            None
14703    7627            None

[14704 rows x 2 columns]

In [27]:
df_tags['solve'] = [1] * len(df_tags)
tag_table = df_tags.pivot_table(index = ["tag"], columns=["target"], values="solve").reindex(index=tag_idx)
tag_X = tag_table.to_numpy()
tag_X = np.nan_to_num(tag_X)

In [28]:
tag_table

target,0,1,2,3,4,5,6,7,8,9,...,7604,7613,7614,7615,7620,7621,7622,7625,7626,7627
tag,,,,,,,,,,,,,,,,,,,,,
math,1.0,1.0,1.0,NaN,1.0,NaN,NaN,1.0,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
graphs,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
implementation,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
dp,NaN,NaN,NaN,1.0,NaN,1.0,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
data_structures,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
implementation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
graph_traversal,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
string,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
dp,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
sorting,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
bruteforcing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
number_theory,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
trees,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
segtree,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
greedy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
bfs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
greedy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
data_structures,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
math,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
binary_search,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
simulation,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## 유저 데이터 전처리

In [29]:
df_user_problems = user_df[['id_to_index', 'target']]

In [30]:
df_user_problems

         id_to_index  target
0                  1       0
1                  1       3
2                  1       5
3                  1       7
4                  1       8
...              ...     ...
2707128        67299       0
2707129        67299       1
2707130        67299       8
2707131        67299    1487
2707132        67299    3633

[2707133 rows x 2 columns]

In [31]:
df_user_problems = df_user_problems[(df_user_problems['id_to_index'] <= 1000)]

In [32]:
df_user_problems['solve'] = [1] * len(df_user_problems)
pivot_table = df_user_problems.pivot_table(index=["id_to_index"], columns=["target"], values="solve")
X = pivot_table.to_numpy()
X = np.nan_to_num(X)

<ipython-input-32-74f793fe73a8>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_user_problems['solve'] = [1] * len(df_user_problems)

In [33]:
pivot_table

target,0,1,2,3,4,5,6,7,8,9,...,7590,7593,7601,7602,7604,7613,7614,7620,7625,7627
id_to_index,,,,,,,,,,,,,,,,,,,,,
1,1.0,NaN,NaN,1.0,NaN,1.0,NaN,1.0,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1.0,1.0,NaN,1.0,NaN,NaN,NaN,NaN,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,1.0,1.0,NaN,1.0,NaN,NaN,NaN,NaN,1.0,NaN,...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,1.0,1.0,NaN,1.0,NaN,NaN,NaN,NaN,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,1.0,1.0,1.0,1.0,NaN,1.0,NaN,NaN,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
991,1.0,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
993,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
995,1.0,1.0,NaN,NaN,NaN,1.0,NaN,NaN,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
997,1.0,1.0,NaN,1.0,NaN,1.0,NaN,NaN,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
999,1.0,1.0,1.0,1.0,NaN,1.0,NaN,NaN,1.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## MF 모델 정의

In [34]:
import numpy as np
from tqdm import tqdm_notebook as tqdm

# Base code : https://github.com/mickeykedia/Matrix-Factorization-ALS/blob/master/ALS%20Python%20Implementation.py
class AlternatingLeastSquares():
    def __init__(self, R, k, reg_param, epochs, verbose=False):
        """
        :param R: rating matrix
        :param k: latent parameter
        :param learning_rate: alpha on weight update
        :param reg_param: beta on weight update
        :param epochs: training epochs
        :param verbose: print status
        """
        self._R = R
        self._num_users, self._num_items = R.shape
        self._k = k
        self._reg_param = reg_param
        self._epochs = epochs
        self._verbose = verbose


    def fit(self):
        # init latent features
        self._users = np.random.normal(size=(self._num_users, self._k))
        self._items = np.random.normal(size=(self._num_items, self._k))

        # train while epochs
        self._training_process = []
        self._user_error = 0; self._item_error = 0;
        for epoch in range(self._epochs):
            for i, Ri in enumerate(self._R):  #user space에 대해서 진행
                self._users[i] = self.user_latent(i, Ri)
                self._user_error = self.cost()

            for j, Rj in enumerate(self._R.T):  #item space에 대해서 update를 진행
                self._items[j] = self.item_latent(j, Rj)
                self._item_error = self.cost()

            cost = self.cost()
            self._training_process.append((epoch, cost))

            # print status
            if self._verbose == True and ((epoch + 1) % 10 == 0):
                print("Iteration: %d ; cost = %.4f" % (epoch + 1, cost))


    def cost(self):
        """
        compute root mean square error
        :return: rmse cost
        """
        xi, yi = self._R.nonzero()
        cost = 0
        for x, y in zip(xi, yi):
            cost += pow(self._R[x, y] - self.get_prediction(x, y), 2)
        return np.sqrt(cost/len(xi))


    def user_latent(self, i, Ri):
        """
        :param error: rating - prediction error
        :param i: user index
        :param Ri: Rating of user index i
        :return: convergence value of user latent of i index
        """

        du = np.linalg.solve(np.dot(self._items.T, np.dot(np.diag(Ri), self._items)) + self._reg_param * np.eye(self._k),
                                   np.dot(self._items.T, np.dot(np.diag(Ri), self._R[i].T))).T
        return du

    def item_latent(self, j, Rj):
        """
        :param error: rating - prediction error
        :param j: item index
        :param Rj: Rating of item index j
        :return: convergence value of itemr latent of j index
        """

        di = np.linalg.solve(np.dot(self._users.T, np.dot(np.diag(Rj), self._users)) + self._reg_param * np.eye(self._k),
                                 np.dot(self._users.T, np.dot(np.diag(Rj), self._R[:, j])))
        return di


    def get_prediction(self, i, j):
        """
        get predicted rating: user_i, item_j
        :return: prediction of r_ij
        """
        return self._users[i, :].dot(self._items[j, :].T)


    def get_complete_matrix(self):
        """
        :return: complete matrix R^
        """
        return self._users.dot(self._items.T)

In [35]:
als = AlternatingLeastSquares(R = X, reg_param = 0.01, epochs=10, verbose=True, k=21)
als.fit()

KeyboardInterrupt: ignored

In [ ]:
als.get_complete_matrix()

## FM 모델 정의

In [ ]:
fm_df = user_df[['id_to_index', 'target','tag']]